"""
This type stub file was generated by pyright.
"""

from math import cos, pi, sin
from typing import Callable

def linear(percent):
    ...

def sine(percent): # -> float:
    ...

def cosine(percent): # -> float:
    ...

def bezier(percent, p1x: float = ..., p1y: float = ..., p2x: float = ..., p2y: float = ...) -> float:
    ...

def get_ease(percent: float, type: str, b_point: list = ...) -> float:
    ...

def get_easing_func(type: str, b_point: list = ...) -> Callable:
    ...

def make_bezier(b_point: list = ...): # -> (x: float) -> float:
    ...

def slicer(time, fromtime, totime, fromposition, toposition, easingtype=...): # -> None:
    ...

